baseurl = "https://nanx.me/hugo-tanka/"
title = "A top the data pile"
author = "Axel Bergman"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Hugo Tanka Theme"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/Axel-Bergman"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = "https://se.linkedin.com/in/axel-bergman-a31623114"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/bergman_axel"
    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
